apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "check-app-server.fullname" . }}-config
  labels:
    {{- include "check-app-server.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.config.spring.datasource.url | quote }}
  SPRING_REDIS_HOST: {{ .Values.config.spring.redis.host | quote }}
  SPRING_REDIS_PORT: {{ .Values.config.spring.redis.port | quote }}
  SPRING_REDIS_DATABASE: {{ .Values.config.spring.redis.database | quote }} 