apiVersion: v1
kind: Secret
metadata:
  name: {{ include "check-app-server.fullname" . }}-secret
  labels:
    {{- include "check-app-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.config.spring.datasource.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.config.spring.datasource.password | quote }}
  SPRING_REDIS_PASSWORD: {{ .Values.config.spring.redis.password | quote }}
  JWT_SECRET: {{ .Values.config.jwt.secret | quote }} 