apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-web.fullname" . }}
  labels:
    {{- include "admin-web.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "admin-web.selectorLabels" . | nindent 4 }} 