# 副本数
replicaCount: 1

# 镜像配置
image:
  repository: check-app-server
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# 服务配置
service:
  type: ClusterIP
  port: 8080

# 持久化存储配置
persistence:
  enabled: true
  # 存储类名，根据K8s集群配置
  storageClass: ""
  # 存储大小
  size: 10Gi
  # 访问模式
  accessMode: ReadWriteOnce
  # 挂载路径
  mountPath: /app/data
  # 子路径配置
  subPaths:
    qrcode: qrcode
    uploads: uploads

# Ingress配置
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: check-app.local
      paths:
        - /
  tls: []

# 资源限制
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# 节点选择器
nodeSelector: {}

# 容忍配置
tolerations: []

# 亲和性配置
affinity: {}

# 环境变量
env:
  SPRING_PROFILES_ACTIVE: prod

# 应用配置
config:
  spring:
    datasource:
      url: jdbc:mysql://mysql:3306/check_app?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: ""
    redis:
      host: redis
      port: 6379
      password: ""
      database: 0
  jwt:
    secret: pensun-check-app-secret-key
    expiration: 86400000
  # 文件存储配置
  qrcode:
    output-dir: /app/data/qrcode
  file:
    upload-dir: /app/data/uploads 