server:
  port: 8080
  mode: debug  # debug or release

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: your_password
  dbname: inspection_app
  charset: utf8mb4
  max_idle_conns: 10
  max_open_conns: 100

jwt:
  secret: your_jwt_secret_key
  expire_hours: 24

log:
  level: debug
  filename: ./logs/app.log
  max_size: 100    # megabytes
  max_age: 30      # days
  max_backups: 7 