server:
  port: 8080
  mode: debug

database:
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  dbname: inspection_db
  charset: utf8mb4
  parseTime: true
  loc: Local

jwt:
  secret: your_jwt_secret_key
  expire: 24  # 24小时 